Repository AL-MASNAI/car-price-analysis-hackathon-team4, pull requests merged in 2025-09, with the labels that each got.

#29 Update README.md
  README.md
Labels: bug, documentation

#43 Fix notebook
  jupyter_notebooks/Visualisation.ipynb
Labels: enhancement

#60 image address fix
  README.md
Labels: documentation

#62 Kanban board
  Media/Git-Kanban-Board.png
Labels: documentation, Administration, process

#67 10 minutes to 5 readme fix
  README.md
Labels: documentation

#68 Revise README for clarity and structure
  README.md
Labels: documentation
